import type { Stock } from "./types"

export const stockMetadata: Omit<Stock, "price" | "change" | "changePercent">[] = [
  // Top 20 Bullish (AI recommends - profitable)
  {
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    volume: 45678000,
    marketCap: "2.15T",
    sector: "Technology",
    prediction: "bullish",
    aiScore: 95,
    targetPrice: 180,
    recommendation: "Strong Buy",
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corporation",
    volume: 23456000,
    marketCap: "3.16T",
    sector: "Technology",
    prediction: "bullish",
    aiScore: 92,
    targetPrice: 500,
    recommendation: "Strong Buy",
  },
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    volume: 56789000,
    marketCap: "3.02T",
    sector: "Technology",
    prediction: "bullish",
    aiScore: 90,
    targetPrice: 250,
    recommendation: "Buy",
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    volume: 28900000,
    marketCap: "2.2T",
    sector: "Technology",
    prediction: "bullish",
    aiScore: 88,
    targetPrice: 200,
    recommendation: "Buy",
  },
  {
    symbol: "META",
    name: "Meta Platforms",
    volume: 18765000,
    marketCap: "1.38T",
    sector: "Technology",
    prediction: "bullish",
    aiScore: 87,
    targetPrice: 650,
    recommendation: "Buy",
  },
  {
    symbol: "AMZN",
    name: "Amazon.com Inc.",
    volume: 34567000,
    marketCap: "2.05T",
    sector: "Consumer",
    prediction: "bullish",
    aiScore: 86,
    targetPrice: 220,
    recommendation: "Buy",
  },
  {
    symbol: "AMD",
    name: "Advanced Micro Devices",
    volume: 45000000,
    marketCap: "220B",
    sector: "Technology",
    prediction: "bullish",
    aiScore: 85,
    targetPrice: 180,
    recommendation: "Buy",
  },
  {
    symbol: "NFLX",
    name: "Netflix Inc.",
    volume: 5600000,
    marketCap: "280B",
    sector: "Technology",
    prediction: "bullish",
    aiScore: 84,
    targetPrice: 750,
    recommendation: "Buy",
  },
  {
    symbol: "V",
    name: "Visa Inc.",
    volume: 8900000,
    marketCap: "550B",
    sector: "Finance",
    prediction: "bullish",
    aiScore: 83,
    targetPrice: 320,
    recommendation: "Buy",
  },
  {
    symbol: "UNH",
    name: "UnitedHealth Group",
    volume: 4567000,
    marketCap: "521B",
    sector: "Healthcare",
    prediction: "bullish",
    aiScore: 82,
    targetPrice: 600,
    recommendation: "Buy",
  },
  {
    symbol: "MA",
    name: "Mastercard Inc.",
    volume: 3200000,
    marketCap: "420B",
    sector: "Finance",
    prediction: "bullish",
    aiScore: 81,
    targetPrice: 480,
    recommendation: "Buy",
  },
  {
    symbol: "LLY",
    name: "Eli Lilly & Co.",
    volume: 4100000,
    marketCap: "750B",
    sector: "Healthcare",
    prediction: "bullish",
    aiScore: 80,
    targetPrice: 850,
    recommendation: "Buy",
  },
  {
    symbol: "GS",
    name: "Goldman Sachs",
    volume: 2800000,
    marketCap: "180B",
    sector: "Finance",
    prediction: "bullish",
    aiScore: 78,
    targetPrice: 550,
    recommendation: "Buy",
  },
  {
    symbol: "CAT",
    name: "Caterpillar Inc.",
    volume: 2100000,
    marketCap: "175B",
    sector: "Industrial",
    prediction: "bullish",
    aiScore: 76,
    targetPrice: 380,
    recommendation: "Buy",
  },
  {
    symbol: "MRK",
    name: "Merck & Co.",
    volume: 8500000,
    marketCap: "320B",
    sector: "Healthcare",
    prediction: "bullish",
    aiScore: 75,
    targetPrice: 140,
    recommendation: "Buy",
  },
  {
    symbol: "KO",
    name: "Coca-Cola Co.",
    volume: 12000000,
    marketCap: "260B",
    sector: "Consumer",
    prediction: "bullish",
    aiScore: 74,
    targetPrice: 70,
    recommendation: "Hold",
  },
  {
    symbol: "PEP",
    name: "PepsiCo Inc.",
    volume: 5600000,
    marketCap: "230B",
    sector: "Consumer",
    prediction: "bullish",
    aiScore: 73,
    targetPrice: 185,
    recommendation: "Hold",
  },
  {
    symbol: "MCD",
    name: "McDonald's Corp.",
    volume: 3400000,
    marketCap: "210B",
    sector: "Consumer",
    prediction: "bullish",
    aiScore: 72,
    targetPrice: 310,
    recommendation: "Hold",
  },
  {
    symbol: "HON",
    name: "Honeywell Intl.",
    volume: 2900000,
    marketCap: "140B",
    sector: "Industrial",
    prediction: "bullish",
    aiScore: 71,
    targetPrice: 225,
    recommendation: "Hold",
  },
  {
    symbol: "TMUS",
    name: "T-Mobile US",
    volume: 4500000,
    marketCap: "200B",
    sector: "Communication",
    prediction: "bullish",
    aiScore: 70,
    targetPrice: 190,
    recommendation: "Hold",
  },

  // Top 20 Bearish (AI does not recommend - not profitable)
  {
    symbol: "INTC",
    name: "Intel Corporation",
    volume: 45678000,
    marketCap: "95B",
    sector: "Technology",
    prediction: "bearish",
    aiScore: 25,
    targetPrice: 18,
    recommendation: "Sell",
  },
  {
    symbol: "DIS",
    name: "Walt Disney Co.",
    volume: 12000000,
    marketCap: "170B",
    sector: "Media",
    prediction: "bearish",
    aiScore: 28,
    targetPrice: 85,
    recommendation: "Sell",
  },
  {
    symbol: "BAC",
    name: "Bank of America",
    volume: 34567000,
    marketCap: "300B",
    sector: "Finance",
    prediction: "bearish",
    aiScore: 32,
    targetPrice: 35,
    recommendation: "Sell",
  },
  {
    symbol: "WMT",
    name: "Walmart Inc.",
    volume: 8900000,
    marketCap: "450B",
    sector: "Consumer",
    prediction: "bearish",
    aiScore: 35,
    targetPrice: 75,
    recommendation: "Hold",
  },
  {
    symbol: "JNJ",
    name: "Johnson & Johnson",
    volume: 7800000,
    marketCap: "380B",
    sector: "Healthcare",
    prediction: "bearish",
    aiScore: 38,
    targetPrice: 145,
    recommendation: "Hold",
  },
  {
    symbol: "PG",
    name: "Procter & Gamble",
    volume: 6700000,
    marketCap: "380B",
    sector: "Consumer",
    prediction: "bearish",
    aiScore: 40,
    targetPrice: 155,
    recommendation: "Hold",
  },
  {
    symbol: "XOM",
    name: "Exxon Mobil",
    volume: 15000000,
    marketCap: "450B",
    sector: "Energy",
    prediction: "bearish",
    aiScore: 30,
    targetPrice: 95,
    recommendation: "Sell",
  },
  {
    symbol: "HD",
    name: "Home Depot",
    volume: 4500000,
    marketCap: "350B",
    sector: "Retail",
    prediction: "bearish",
    aiScore: 38,
    targetPrice: 340,
    recommendation: "Hold",
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase",
    volume: 9000000,
    marketCap: "580B",
    sector: "Finance",
    prediction: "bearish",
    aiScore: 42,
    targetPrice: 190,
    recommendation: "Hold",
  },
  {
    symbol: "TSLA",
    name: "Tesla Inc.",
    volume: 89000000,
    marketCap: "780B",
    sector: "Automotive",
    prediction: "bearish",
    aiScore: 30,
    targetPrice: 200,
    recommendation: "Sell",
  },
  {
    symbol: "WFC",
    name: "Wells Fargo & Co.",
    volume: 18000000,
    marketCap: "185B",
    sector: "Finance",
    prediction: "bearish",
    aiScore: 33,
    targetPrice: 48,
    recommendation: "Sell",
  },
  {
    symbol: "C",
    name: "Citigroup Inc.",
    volume: 14000000,
    marketCap: "120B",
    sector: "Finance",
    prediction: "bearish",
    aiScore: 35,
    targetPrice: 55,
    recommendation: "Sell",
  },
  {
    symbol: "PFE",
    name: "Pfizer Inc.",
    volume: 32000000,
    marketCap: "160B",
    sector: "Healthcare",
    prediction: "bearish",
    aiScore: 36,
    targetPrice: 26,
    recommendation: "Sell",
  },
  {
    symbol: "CVX",
    name: "Chevron Corp.",
    volume: 8500000,
    marketCap: "280B",
    sector: "Energy",
    prediction: "bearish",
    aiScore: 37,
    targetPrice: 140,
    recommendation: "Hold",
  },
  {
    symbol: "BA",
    name: "Boeing Co.",
    volume: 7200000,
    marketCap: "130B",
    sector: "Industrial",
    prediction: "bearish",
    aiScore: 28,
    targetPrice: 165,
    recommendation: "Sell",
  },
  {
    symbol: "GE",
    name: "General Electric",
    volume: 6100000,
    marketCap: "180B",
    sector: "Industrial",
    prediction: "bearish",
    aiScore: 40,
    targetPrice: 155,
    recommendation: "Hold",
  },
  {
    symbol: "VZ",
    name: "Verizon Comm.",
    volume: 15000000,
    marketCap: "170B",
    sector: "Communication",
    prediction: "bearish",
    aiScore: 38,
    targetPrice: 38,
    recommendation: "Hold",
  },
  {
    symbol: "T",
    name: "AT&T Inc.",
    volume: 28000000,
    marketCap: "130B",
    sector: "Communication",
    prediction: "bearish",
    aiScore: 32,
    targetPrice: 17,
    recommendation: "Sell",
  },
  {
    symbol: "CMCSA",
    name: "Comcast Corp.",
    volume: 18000000,
    marketCap: "160B",
    sector: "Communication",
    prediction: "bearish",
    aiScore: 36,
    targetPrice: 38,
    recommendation: "Hold",
  },
  {
    symbol: "ABBV",
    name: "AbbVie Inc.",
    volume: 7500000,
    marketCap: "310B",
    sector: "Healthcare",
    prediction: "bearish",
    aiScore: 42,
    targetPrice: 165,
    recommendation: "Hold",
  },
]

const defaultPrices: Record<string, { price: number; change: number; changePercent: number }> = {
  NVDA: { price: 135.5, change: 2.45, changePercent: 1.84 },
  MSFT: { price: 425.8, change: 5.2, changePercent: 1.24 },
  AAPL: { price: 195.6, change: 1.85, changePercent: 0.95 },
  GOOGL: { price: 177.5, change: 2.3, changePercent: 1.31 },
  META: { price: 585.4, change: 8.5, changePercent: 1.47 },
  AMZN: { price: 198.2, change: 3.1, changePercent: 1.59 },
  AMD: { price: 138.75, change: 4.2, changePercent: 3.12 },
  NFLX: { price: 685.3, change: 12.5, changePercent: 1.86 },
  V: { price: 287.4, change: 2.8, changePercent: 0.98 },
  UNH: { price: 567.8, change: 4.5, changePercent: 0.8 },
  MA: { price: 465.2, change: 3.8, changePercent: 0.82 },
  LLY: { price: 798.5, change: 15.2, changePercent: 1.94 },
  GS: { price: 512.3, change: 8.4, changePercent: 1.67 },
  CAT: { price: 358.7, change: 5.6, changePercent: 1.59 },
  MRK: { price: 128.4, change: 1.9, changePercent: 1.5 },
  KO: { price: 62.8, change: 0.45, changePercent: 0.72 },
  PEP: { price: 172.3, change: 1.2, changePercent: 0.7 },
  MCD: { price: 295.6, change: 2.1, changePercent: 0.71 },
  HON: { price: 212.4, change: 1.8, changePercent: 0.85 },
  TMUS: { price: 178.9, change: 2.3, changePercent: 1.3 },
  INTC: { price: 24.3, change: -0.45, changePercent: -1.82 },
  DIS: { price: 95.6, change: -1.2, changePercent: -1.24 },
  BAC: { price: 42.15, change: -0.35, changePercent: -0.82 },
  WMT: { price: 82.5, change: -0.65, changePercent: -0.78 },
  JNJ: { price: 156.4, change: -0.9, changePercent: -0.57 },
  PG: { price: 168.2, change: -0.75, changePercent: -0.44 },
  XOM: { price: 108.5, change: -1.85, changePercent: -1.68 },
  HD: { price: 375.6, change: -2.4, changePercent: -0.63 },
  JPM: { price: 205.3, change: -1.1, changePercent: -0.53 },
  TSLA: { price: 248.9, change: -5.6, changePercent: -2.2 },
  WFC: { price: 58.4, change: -0.72, changePercent: -1.22 },
  C: { price: 62.8, change: -0.95, changePercent: -1.49 },
  PFE: { price: 28.5, change: -0.42, changePercent: -1.45 },
  CVX: { price: 152.6, change: -1.8, changePercent: -1.17 },
  BA: { price: 178.3, change: -3.2, changePercent: -1.76 },
  GE: { price: 168.5, change: -1.2, changePercent: -0.71 },
  VZ: { price: 41.2, change: -0.28, changePercent: -0.67 },
  T: { price: 19.8, change: -0.15, changePercent: -0.75 },
  CMCSA: { price: 42.3, change: -0.38, changePercent: -0.89 },
  ABBV: { price: 178.6, change: -1.4, changePercent: -0.78 },
}

export const stocksData: Stock[] = stockMetadata.map((meta) => ({
  ...meta,
  price: defaultPrices[meta.symbol]?.price || 100,
  change: defaultPrices[meta.symbol]?.change || 0,
  changePercent: defaultPrices[meta.symbol]?.changePercent || 0,
}))

export function getTopBullish(): Stock[] {
  return stocksData
    .filter((s) => s.prediction === "bullish")
    .sort((a, b) => b.aiScore - a.aiScore)
    .slice(0, 10)
}

export function getTopBearish(): Stock[] {
  return stocksData
    .filter((s) => s.prediction === "bearish")
    .sort((a, b) => a.aiScore - b.aiScore)
    .slice(0, 10)
}

export function getAllStocks(): Stock[] {
  return stocksData
}

export function getStockBySymbol(symbol: string): Stock | undefined {
  return stocksData.find((s) => s.symbol === symbol)
}

export function updateStockPrice(stock: Stock, liveData: { c: number; d: number; dp: number }): Stock {
  return {
    ...stock,
    price: liveData.c,
    change: liveData.d || 0,
    changePercent: liveData.dp || 0,
  }
}

export function simulatePriceChange(stock: Stock): Stock {
  const volatility = stock.prediction === "bullish" ? 0.02 : 0.03
  const direction = stock.prediction === "bullish" ? 0.6 : 0.4
  const random = Math.random()
  const changePercent = (random > direction ? 1 : -1) * Math.random() * volatility * 100
  const change = stock.price * (changePercent / 100)

  return {
    ...stock,
    price: Math.max(0.01, stock.price + change),
    change: change,
    changePercent: changePercent,
  }
}
